# k8s secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-cloud-proxy.fullname" . }}
  labels:
    {{- include "grafana-cloud-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  prometheus.yml: |
    remote_read:
      - url: "https://{{.Values.prometheus.host}}/api/prom/api/v1/read"
        basic_auth:
          username: "{{.Values.prometheus.username}}"
          password: "{{.Values.prometheus.password}}"
